[build]
  base = "frontend/"
  command = "npm run build"
  publish = "build"

[[plugins]]
  package = "@netlify/plugin-monorepo"

[context.production]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../frontend/" 